// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROJETO.Models;

namespace PROJETO.Migrations
{
    [DbContext(typeof(EventShareContext))]
    partial class EventShareContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PROJETO.Models.EventoCategoriaTbl", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("categoria_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoriaNome")
                        .HasColumnName("categoria_nome")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("CategoriaId")
                        .HasName("PK__evento_c__DB875A4FF7544FBE");

                    b.ToTable("evento_categoria_tbl");
                });

            modelBuilder.Entity("PROJETO.Models.EventoEspacoTbl", b =>
                {
                    b.Property<int>("EspacoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("espaco_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EspacoNome")
                        .HasColumnName("espaco_nome")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("EspacoId")
                        .HasName("PK__evento_e__01BC6094BBFE2231");

                    b.ToTable("evento_espaco_tbl");
                });

            modelBuilder.Entity("PROJETO.Models.EventoStatusTbl", b =>
                {
                    b.Property<int>("EventoStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("evento_status_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventoStatusNome")
                        .HasColumnName("evento_status_nome")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("EventoStatusId")
                        .HasName("PK__evento_s__F2753B700300C754");

                    b.ToTable("evento_status_tbl");
                });

            modelBuilder.Entity("PROJETO.Models.EventoTbl", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("evento_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CriadorUsuarioId")
                        .HasColumnName("criador_usuario_id")
                        .HasColumnType("int");

                    b.Property<int?>("EventoCategoriaId")
                        .HasColumnName("evento_categoria_id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EventoData")
                        .HasColumnName("evento_data")
                        .HasColumnType("date");

                    b.Property<string>("EventoDescricao")
                        .HasColumnName("evento_descricao")
                        .HasColumnType("text");

                    b.Property<int>("EventoEspacoId")
                        .HasColumnName("evento_espaco_id")
                        .HasColumnType("int");

                    b.Property<string>("EventoHorarioComeco")
                        .HasColumnName("evento_horario_comeco")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("EventoHorarioFim")
                        .HasColumnName("evento_horario_fim")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("EventoImagem")
                        .HasColumnName("evento_imagem")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("EventoNome")
                        .HasColumnName("evento_nome")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int?>("EventoStatusId")
                        .HasColumnName("evento_status_id")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsavelUsuarioId")
                        .HasColumnName("responsavel_usuario_id")
                        .HasColumnType("int");

                    b.HasKey("EventoId")
                        .HasName("PK__evento_t__1850C3AD331734B5");

                    b.HasIndex("CriadorUsuarioId");

                    b.HasIndex("EventoCategoriaId");

                    b.HasIndex("EventoEspacoId");

                    b.HasIndex("EventoStatusId");

                    b.HasIndex("ResponsavelUsuarioId");

                    b.ToTable("evento_tbl");
                });

            modelBuilder.Entity("PROJETO.Models.UsuarioTbl", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("usuario_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UsuarioComunidade")
                        .HasColumnName("usuario_comunidade")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioEmail")
                        .IsRequired()
                        .HasColumnName("usuario_email")
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioImagem")
                        .HasColumnName("usuario_imagem")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("UsuarioNome")
                        .HasColumnName("usuario_nome")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.Property<string>("UsuarioSenha")
                        .HasColumnName("usuario_senha")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<int?>("UsuarioTipoId")
                        .HasColumnName("usuario_tipo_id")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId")
                        .HasName("PK__usuario___2ED7D2AFB0CD79B4");

                    b.HasIndex("UsuarioTipoId");

                    b.ToTable("usuario_tbl");
                });

            modelBuilder.Entity("PROJETO.Models.UsuarioTipoTbl", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("tipo_id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipoNome")
                        .HasColumnName("tipo_nome")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50)
                        .IsUnicode(false);

                    b.HasKey("TipoId")
                        .HasName("PK__usuario___6EA5A01B2E59D269");

                    b.ToTable("usuario_tipo_tbl");
                });

            modelBuilder.Entity("PROJETO.Models.EventoTbl", b =>
                {
                    b.HasOne("PROJETO.Models.UsuarioTbl", "CriadorUsuario")
                        .WithMany("EventoTblCriadorUsuario")
                        .HasForeignKey("CriadorUsuarioId")
                        .HasConstraintName("FK__evento_tb__criad__44FF419A");

                    b.HasOne("PROJETO.Models.EventoCategoriaTbl", "EventoCategoria")
                        .WithMany("EventoTbl")
                        .HasForeignKey("EventoCategoriaId")
                        .HasConstraintName("FK__evento_tb__event__4222D4EF");

                    b.HasOne("PROJETO.Models.EventoEspacoTbl", "EventoEspaco")
                        .WithMany("EventoTbl")
                        .HasForeignKey("EventoEspacoId")
                        .HasConstraintName("FK__evento_tb__event__4316F928")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROJETO.Models.EventoStatusTbl", "EventoStatus")
                        .WithMany("EventoTbl")
                        .HasForeignKey("EventoStatusId")
                        .HasConstraintName("FK__evento_tb__event__440B1D61");

                    b.HasOne("PROJETO.Models.UsuarioTbl", "ResponsavelUsuario")
                        .WithMany("EventoTblResponsavelUsuario")
                        .HasForeignKey("ResponsavelUsuarioId")
                        .HasConstraintName("FK__evento_tb__respo__45F365D3");
                });

            modelBuilder.Entity("PROJETO.Models.UsuarioTbl", b =>
                {
                    b.HasOne("PROJETO.Models.UsuarioTipoTbl", "UsuarioTipo")
                        .WithMany("UsuarioTbl")
                        .HasForeignKey("UsuarioTipoId")
                        .HasConstraintName("FK__usuario_t__usuar__3F466844");
                });
#pragma warning restore 612, 618
        }
    }
}
